import { useTranslations } from 'next-intl';
import { getTranslations } from 'next-intl/server';
import Link from 'next/link';
import LanguageSwitcher from '../../../components/LanguageSwitcher';

export default async function Home({ params: { locale } }: { params: { locale: string } }) {
  const t = await getTranslations('home');

  return (
    <div className="min-h-screen bg-gradient-to-b from-blue-50 to-white">
      {/* Header with Language Switcher */}
      <header className="border-b bg-white">
        <div className="container mx-auto px-4 py-4 flex justify-between items-center">
          <h1 className="text-2xl font-bold text-blue-600">Athera Run</h1>
          <div className="flex items-center gap-4">
            <LanguageSwitcher />
            <Link 
              href={`/${locale}/login`}
              className="px-4 py-2 text-blue-600 hover:text-blue-800"
            >
              {locale === 'pt-BR' ? 'Entrar' : locale === 'en-US' ? 'Login' : 'Iniciar sesión'}
            </Link>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <main className="container mx-auto px-4 py-16">
        <div className="text-center max-w-4xl mx-auto">
          <h1 className="text-5xl md:text-6xl font-bold text-gray-900 mb-6">
            {t('hero')}
          </h1>
          <p className="text-xl text-gray-600 mb-8">
            {t('heroSubtitle')}
          </p>
          <div className="flex gap-4 justify-center">
            <Link
              href={`/${locale}/signup`}
              className="px-8 py-4 bg-blue-600 text-white rounded-lg hover:bg-blue-700 text-lg font-semibold"
            >
              {t('getStarted')}
            </Link>
            <Link
              href="#features"
              className="px-8 py-4 border-2 border-blue-600 text-blue-600 rounded-lg hover:bg-blue-50 text-lg font-semibold"
            >
              {t('learnMore')}
            </Link>
          </div>
        </div>

        {/* Features */}
        <div id="features" className="mt-24 grid md:grid-cols-3 gap-8">
          <div className="bg-white p-8 rounded-xl shadow-md">
            <div className="text-4xl mb-4">🤖</div>
            <h3 className="text-xl font-bold mb-2">
              {locale === 'pt-BR' ? 'IA Especializada' : locale === 'en-US' ? 'Specialized AI' : 'IA Especializada'}
            </h3>
            <p className="text-gray-600">
              {locale === 'pt-BR' 
                ? 'Planos gerados por GPT-4o com metodologia científica'
                : locale === 'en-US'
                ? 'Plans generated by GPT-4o with scientific methodology'
                : 'Planes generados por GPT-4o con metodología científica'}
            </p>
          </div>

          <div className="bg-white p-8 rounded-xl shadow-md">
            <div className="text-4xl mb-4">🎯</div>
            <h3 className="text-xl font-bold mb-2">
              {locale === 'pt-BR' ? '100% Personalizado' : locale === 'en-US' ? '100% Personalized' : '100% Personalizado'}
            </h3>
            <p className="text-gray-600">
              {locale === 'pt-BR'
                ? 'Baseado em seus dados, objetivos e disponibilidade'
                : locale === 'en-US'
                ? 'Based on your data, goals and availability'
                : 'Basado en tus datos, objetivos y disponibilidad'}
            </p>
          </div>

          <div className="bg-white p-8 rounded-xl shadow-md">
            <div className="text-4xl mb-4">🔬</div>
            <h3 className="text-xl font-bold mb-2">
              {locale === 'pt-BR' ? 'Científico' : locale === 'en-US' ? 'Scientific' : 'Científico'}
            </h3>
            <p className="text-gray-600">
              {locale === 'pt-BR'
                ? 'Metodologia Jack Daniels e análise VDOT'
                : locale === 'en-US'
                ? 'Jack Daniels methodology and VDOT analysis'
                : 'Metodología Jack Daniels y análisis VDOT'}
            </p>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-gray-900 text-white py-8 mt-24">
        <div className="container mx-auto px-4 text-center">
          <p>© 2025 Athera Run - {locale === 'pt-BR' ? 'Todos os direitos reservados' : locale === 'en-US' ? 'All rights reserved' : 'Todos los derechos reservados'}</p>
        </div>
      </footer>
    </div>
  );
}
